name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - pip=20.3.3
  - mlflow=1.19.0
  - scikit-learn=0.24.1
  - matplotlib=3.4.3
  - pillow=8.1.2
  - numpy=1.23.5
  - pip:
      - wandb==0.10.31
